package com.android.common.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.common.bean.Task;
import com.android.common.bean.User;
import com.android.common.bean.Team;

import com.android.common.greendao.TaskDao;
import com.android.common.greendao.UserDao;
import com.android.common.greendao.TeamDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig teamDaoConfig;

    private final TaskDao taskDao;
    private final UserDao userDao;
    private final TeamDao teamDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        teamDaoConfig = daoConfigMap.get(TeamDao.class).clone();
        teamDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        teamDao = new TeamDao(teamDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(User.class, userDao);
        registerDao(Team.class, teamDao);
    }
    
    public void clear() {
        taskDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        teamDaoConfig.clearIdentityScope();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TeamDao getTeamDao() {
        return teamDao;
    }

}
